package resource

import (
	"context"
	"fmt"
	"net/http"

	"github.com/forgers-tech/terraform-provider-webhookr/internal/client"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = (*EndpointResource)(nil)

type EndpointResource struct {
	client *client.Client
}

type endpointModel struct {
	ID        types.String `tfsdk:"id"`
	ProjectID types.String `tfsdk:"project_id"`
	Name      types.String `tfsdk:"name"`
	Slug      types.String `tfsdk:"slug"`
	IsActive  types.Bool   `tfsdk:"is_active"`
	CreatedAt types.String `tfsdk:"created_at"`
	UpdatedAt types.String `tfsdk:"updated_at"`
}

type endpointAPIResponse struct {
	ID        string `json:"id"`
	ProjectID string `json:"projectId"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	IsActive  bool   `json:"isActive"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

func NewEndpointResource() resource.Resource {
	return &EndpointResource{}
}

func (r *EndpointResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_endpoint"
}

func (r *EndpointResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Webhookr endpoint within a project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Unique identifier of the endpoint.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Required:    true,
				Description: "ID of the parent project.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Display name of the endpoint (max 100 characters).",
			},
			"slug": schema.StringAttribute{
				Computed:    true,
				Description: "URL-safe slug generated by the API (10-character nanoid).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"is_active": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
				Description: "Whether the endpoint is active and accepts incoming events.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "RFC3339 timestamp of when the endpoint was created.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: "RFC3339 timestamp of the last endpoint update.",
			},
		},
	}
}

func (r *EndpointResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type",
			fmt.Sprintf("expected *client.Client, got %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *EndpointResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan endpointModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]any{
		"name":     plan.Name.ValueString(),
		"isActive": plan.IsActive.ValueBool(),
	}
	path := endpointPath(plan.ProjectID.ValueString(), "")
	var result endpointAPIResponse
	status, err := r.client.Do(ctx, http.MethodPost, path, body, &result)
	if err != nil {
		resp.Diagnostics.AddError("Error creating endpoint", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status creating endpoint",
			fmt.Sprintf("expected 201, got %d", status))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, endpointAPIToModel(result))...)
}

func (r *EndpointResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state endpointModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	path := endpointPath(state.ProjectID.ValueString(), state.ID.ValueString())
	var result endpointAPIResponse
	status, err := r.client.Do(ctx, http.MethodGet, path, nil, &result)
	if err != nil {
		resp.Diagnostics.AddError("Error reading endpoint", err.Error())
		return
	}
	if status == http.StatusNotFound {
		resp.State.RemoveResource(ctx)
		return
	}
	if status != http.StatusOK {
		resp.Diagnostics.AddError("Unexpected status reading endpoint",
			fmt.Sprintf("expected 200, got %d", status))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, endpointAPIToModel(result))...)
}

func (r *EndpointResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan endpointModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state endpointModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]any{
		"name":     plan.Name.ValueString(),
		"isActive": plan.IsActive.ValueBool(),
	}
	path := endpointPath(state.ProjectID.ValueString(), state.ID.ValueString())
	var result endpointAPIResponse
	status, err := r.client.Do(ctx, http.MethodPatch, path, body, &result)
	if err != nil {
		resp.Diagnostics.AddError("Error updating endpoint", err.Error())
		return
	}
	if status != http.StatusOK {
		resp.Diagnostics.AddError("Unexpected status updating endpoint",
			fmt.Sprintf("expected 200, got %d", status))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, endpointAPIToModel(result))...)
}

func (r *EndpointResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state endpointModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	path := endpointPath(state.ProjectID.ValueString(), state.ID.ValueString())
	status, err := r.client.Do(ctx, http.MethodDelete, path, nil, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting endpoint", err.Error())
		return
	}
	if status == http.StatusNotFound {
		return
	}
	if status != http.StatusOK {
		resp.Diagnostics.AddError("Unexpected status deleting endpoint",
			fmt.Sprintf("expected 200, got %d", status))
		return
	}
}

func endpointPath(projectID, endpointID string) string {
	base := "/v1/projects/" + projectID + "/endpoints"
	if endpointID == "" {
		return base
	}
	return base + "/" + endpointID
}

func endpointAPIToModel(e endpointAPIResponse) endpointModel {
	return endpointModel{
		ID:        types.StringValue(e.ID),
		ProjectID: types.StringValue(e.ProjectID),
		Name:      types.StringValue(e.Name),
		Slug:      types.StringValue(e.Slug),
		IsActive:  types.BoolValue(e.IsActive),
		CreatedAt: types.StringValue(e.CreatedAt),
		UpdatedAt: types.StringValue(e.UpdatedAt),
	}
}
